%% Single muscle PCA with whole 30s then divide into windows to look
%   at association between SD for FPC and other vars across windows
day = 'stretch';
level = 'submax10';
time = 'before';
mus = 'MG';
win = 'w1';

% SINGLE MUSCLE - MG
PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30 = PCAiterfunc30_singleMuscle(PFdata.(day).(level).MUdata.(time).MG);

%% Break into windows
for w = 1:30
    s = PFdata.(day).(level).MUdata.(time).w1.starts(w)-PFdata.(day).(level).MUdata.(time).start+1;
    e = PFdata.(day).(level).MUdata.(time).w1.endds(w)-PFdata.(day).(level).MUdata.(time).start+1;
    fpc = PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30.coeffs_mean(end,:);
    fpcsec = fpc(s:e);
    PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30.w1.sections{w} = fpcsec;
    PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30.w1.sd(w) = std(fpcsec);
end

%% Steps form Indiv_MUs script

% IDRs
clear('rawidrs','idrfilts')

 % IDRs
    for mu = 1:length(PFdata.(day).(level).MUdata.(time).(mus).rawlines)
        len = length(PFdata.(day).(level).MUdata.(time).(mus).binary);
        isivec = PFdata.(day).(level).MUdata.(time).(mus).binary_ISI;
        isivec(isivec == 0) = NaN;
        if isempty(PFdata.(day).(level).MUdata.(time).(mus).rawlines{mu})
        elseif isnan(PFdata.(day).(level).MUdata.(time).(mus).rawlines{mu})
        else
            rawidrs(mu,:) = PFdata.(day).(level).MUdata.(time).(mus).rawlines{mu};
            temp = PFdata.(day).(level).MUdata.(time).(mus).rawlines{mu};
            start = find(~isnan(temp),1,'first');
            endd = find(~isnan(temp),1,'last');
            temp = temp(start:endd);
            raw = highpass(temp,0.75,2000);
            temp = conv(temp,hann(800),'same');
            temp = highpass(temp,0.75,2000);
            nans1 = repelem(NaN,start-1);
            nans2 = repelem(NaN,(len-endd));
            idrfilts(mu,:) = horzcat(nans1,temp,nans2);
            rawidrs(mu,:) = horzcat(nans1,raw,nans2);
        end
    end
clear('MUvec','MUvecRaw','fcc_raw','fcc_smooth','cors_smooth','cors_raw')

for w = 1:30
    
    s = PFdata.(day).(level).MUdata.(time).(win).starts(w);
    e = PFdata.(day).(level).MUdata.(time).(win).endds(w);
    num = size(PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.raw.(win).coeffs_mean{1,w},1);

    % Comparisons with individual MUs and grouped
    
    MUvec = idrfilts(:,s:e);
    MUvecRaw = rawidrs(:,s:e);
    fcc_raw = PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.raw.(win).coeffs_mean{1,w}(num,:);
    fcc_smooth = PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.(win).coeffs_mean{1,w}(num,:);
    for mu = 1:size(MUvec,1)
        if sum(MUvec(mu,:)) == 0
        else
        % Cross correlation between individual MUs and FCC
        [r,lag] = xcorr(MUvecRaw(mu,:),fcc_raw,200,'normalized');
        [cors_raw(w,mu),ind] = max(r); lag_raw(w,mu) = lag(ind);
        [r,lag] = xcorr(MUvec(mu,:),fcc_smooth,200,'normalized');
        [cors_smooth(w,mu),ind] = max(r); lag_smooth(w,mu) = lag(ind);
        end
    end
end

    cors_smooth(cors_smooth == 0) = NaN;
    cors_raw(cors_raw == 0) = NaN;

%% Scatter plots
set(gcf, 'Renderer', 'painters');
% SMOOTHED
for w = 1:30
    lens(w) = length(PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.(win).explained_means{w});
end
n = min(lens);

for w = 1:30 % SMOOTHED
    dat(w) = PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.(win).explained_means{w}(n);
end

fpc_std = PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30.w1.sd;

t = tiledlayout(1,2);
title(t,'Full 30-s PCA divided into same 1-s windows - Smoothed data - MG')
% By 1-s Windows: SD for FPC vs Median XCorr between smoothed IDRs and FPC
nexttile
    scatter(nanmedian(cors_smooth,2),fpc_std,'r','filled') 
    title('Median XCorr between individual MUs and FPC ~ SD for FPC')
    xlabel('Median xcorr between smoothed IDRs and FPC')
    ylabel('SD for FPC')
    legend('1-s windows')
% By 1-s Windows: SD for FPC vs Mean % Explained by FPC
nexttile
    scatter(dat,fpc_std,'g','filled') 
    title('Mean % Explained by FPC ~ SD for FPC')
    ylabel('SD for FPC')
    xlabel('Mean % explained by FPC')
    legend('1-s windows') 
    
%% How does amplitude differ between coeffs generated by 1-s windowed and 30-s PCA?

tiledlayout(6,5)
for w = 1:30
    nexttile
    num = size(PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.(win).coeffs_mean{1,w},1);
    yyaxis left
    plot(PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.w30.(win).sections{w},'b-')
    hold on;
    yyaxis right
    plot(PFdata.(day).(level).MUdata.(time).(mus).PCA.iter.(win).coeffs_mean{1,w}(num,:),'r')
end
